### ISSUE TITLE
its popping up an error 

### ISSUE THREAD

**Issue by sirantifreeze** [ScobraScope/dankmemer-farm#3]
![9](https://user-images.githubusercontent.com/69359687/154197397-ba9707ae-d362-4828-9010-44f97b8145b1.png)

**Comment by Legoluke01** [comment]
make sure you have all the required libraries installed.
`pip install requests`

**Comment by sirantifreeze** [comment]
how do i do that?

**Comment by Legoluke01** [comment]
via a command prompt opened in the folder

**Comment by sirantifreeze** [comment]
![image](https://user-images.githubusercontent.com/69359687/154199551-b64c189f-ea70-4610-b404-d8ba63fa3a1d.png)
this is what it said

**Comment by sirantifreeze** [comment]
nvm i got my  friemd to help

**Comment by 6A31** [comment]
@Legoluke01 dang.... thanks a lot... 👍
