### ISSUE TITLE
i have no idea coz i am a newbie

### ISSUE THREAD

**Issue by GoldeFinger69420** [ScobraScope/dankmemer-farm#4]
i entered the token text but i have no idea what the next step is, do i need to put the main.py into the same folder or what ...
![image](https://user-images.githubusercontent.com/100109038/155926247-94d3943b-721c-46f0-b865-eb3823434d52.png)

**Comment by jinja365** [comment]
do py -m pip install requests

**Comment by 6A31** [comment]
Still questions?

**Comment by 6A31** [comment]
No answer
