### ISSUE TITLE
pls share max is outdated +suggestions

### ISSUE THREAD

**Issue by 0b9** [ScobraScope/dankmemer-farm#5]
Dank Memer made a change to the bot, pls share max no longer works. I'd suggest you remove it completely or replace it with pls dep max
You can no longer share coins if the main account is not online. The only way to share coins now is to use pls trade

A few other suggestions:
Don't add the _random text to bypass the bot protection_ before the random text

If possible: Add pls work, pls highlow, pls postmeme

**Comment by 6A31** [comment]
Sadly, the way I interacted with discord doesn't allow me to update to the new commands.

It would take an entire re-write to come up with a fix. 

Sorry.
