### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by ColegoneCrazy** [ScobraScope/dankmemer-farm#6]
IT WILL RUN FOR 24 HOURS THAN DANK MEMER WILL LOCK ALL UR ACCOUNTS + BLACKLIST YOUR MAIN FOR 3 MONTHS (If you transferred Dank Memer Coins)
DISCORD ALSO TERMINATED MY ACCOUNT WHILE USING THIS, THEY TERMINATED MY MAIN DISCORD ACCOUNT SO DONT USE PLEASE

**Comment by 6A31** [comment]
Hey, sorry to hear that.

It is mentioned that the script is outdated and that running it for long periods of time can get your account banned by dankmemer or even locked. 

It is always reccomend to do things like this on alt accounts. The purpose of the whole transfer system is to keep losses to a minimum when accounts are banned.
