### ISSUE TITLE
dank memer change to slash command

### ISSUE THREAD

**Issue by YWYin1** [ScobraScope/dankmemer-farm#7]
pls help me 
pls command cant use in dank memer now

**Comment by 6A31** [comment]
Hey there. It has come to my attention that the newest Dankmemer script has broken my farming script.

I am still unsure if I will update the script. For now this repo is depreciated, as stated in the readme.md

There might be updates in the future, depending on my motivation on the project.

**Comment by Snowwy513** [comment]
> 

i have another Grinder with slash command if u want it dm me on Snowwy#3260
